apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
spec:
  selector:
    matchLabels:
      name: log-agent
  template:
    metadata:
      labels:
        name: log-agent
    spec:
      containers:
        - name: log-agent
          image: busybox
          command: ["sh", "-c", "watch -n 5 'tail -f /app/logs/*.log'"]
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          hostPath:
            path: /var/log/app
            type: DirectoryOrCreate
