apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: chesnokoff/app:v1
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: config
              mountPath: /app/config
      volumes:
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            name: app-config
