server:
  port: ${SERVER_PORT:8085}

file:
  path: ${FILE_PATH:./app.log}

message:
  welcome: ${MESSAGE_WELCOME:"Default welcome!"}

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:INFO}
